AllCops:
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - node_modules/**/*
    - vendor/**/*
    - bin/*
    - lib/tasks/*
    - spec/**/*
    - config/initializers/shrine.rb
    - .circleci/*
    - db/migrate/*
    - db/schema.rb

# Rails:
#   Enabled: true

# Rails/DynamicFindBy:
#   Enabled: false

# Rails/FindBy:
#   Enabled: false

# Style/FrozenStringLiteralComment:
#   Enabled: false

# Style/EmptyMethod:
#   Enabled: false

# Style/AsciiComments:
#   Enabled: false

Style/Documentation:
  Enabled: false

# Style/ClassAndModuleChildren:
#   Enabled: false

# Style/SafeNavigation:
#   Exclude:
#     - app/models/data_table/params.rb

# Style/TrailingCommaInArrayLiteral:
#   Enabled: false

# Style/TrailingCommaInArguments:
#   Enabled: false

# Style/GuardClause:
#   Enabled: false

# Style/RescueModifier:
#   Enabled: false

# Metrics/LineLength:
#   Max: 140

# Metrics/MethodLength:
#   Max: 40

# Metrics/AbcSize:
#   Max: 50

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
    - Guardfile

# Metrics/ClassLength:
#   Max: 200

# Metrics/CyclomaticComplexity:
#   Max: 10

# Metrics/PerceivedComplexity:
#   Max: 12

# Lint/SuppressedException:
#   Exclude:
#     - 'config/unicorn/*.rb'
#     - .pryrc

# Lint/ReturnInVoidContext:
#   Exclude:
#     - 'config/initializers/shrine.rb'

# Lint/ShadowingOuterLocalVariable:
#   Exclude:
#     - 'spec/rails_helper.rb'

# Lint/SuppressedException:
#   Enabled: false

# Style/RescueStandardError:
#   Enabled: false

Layout/LineLength:
  Enabled: false
